include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    - example/**
  enable-experiment:
    - non-nullable
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    avoid_print: true