targets:
  $default:
    builders:
      renderable:
        generate_for: ["example/*"]

builders:
  renderable:
    import: "package:renderable/builder.dart"
    builder_factories: ["renderableBuilder"]
    build_extensions: {".dart": [".renderable.g.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
