targets:
  $default:
    builders:
      renderable:
        generate_for:
          - example/**

builders:
  renderable:
    import: "package:renderable/builder.dart"
    builder_factories:
      - htmlTemplateBuilder
    auto_apply: root_package
    build_extensions:
      .html: [".html.dart"]
    build_to: source