targets:
  $default:
    builders:
      renderable:
        generate_for:
        - example/*

builders:
  renderable:
    import: "package:renderable/builder.dart"
    builder_factories: ["templateGenerator"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: dependents
    build_to: source
