name: renderable
description: An simple (and not yet powerful) template language for Dart like Jinja or Stencil.
version: 0.0.5

environment:
  sdk: '>=2.8.2 <3.0.0'

dependencies:
  analyzer: any
  build: any
  meta: any
  path: any
  source_gen: any
  string_scanner: any

dev_dependencies:
  code_builder: any
  dart_style: any
  build_runner: any
  pedantic: any
