name: renderable
description: An simple template language for Dart like Jinja or Stencil.
version: 1.0.0-dev+23

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  analyzer: any
  build: any
  meta: any
  path: any
  string_scanner: any

dev_dependencies:
  build_runner: any
  dart_style: any
  pedantic: any
  test: any
