name: renderable
description: Testing features for Jinja.dart.
version: 1.0.0-dev+90

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  # build: any
  meta: ^1.3.0
  path: ^1.8.0
  string_scanner: ^1.1.0

dev_dependencies:
  # build_runner: any
  pedantic: ^1.10.0
  stack_trace: ^1.10.0
  test: ^1.16.2
