name: renderable
description: Testing features for Jinja.dart.
version: 1.0.0-dev+96
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0
  path: ^1.8.0
  string_scanner: ^1.1.0
  textwrap:
    path: packages/textwrap.dart

dev_dependencies:
  pedantic: ^1.10.0
  stack_trace: ^1.10.0
  test: ^1.16.2
