name: renderable
description: An simple (and not yet powerful) template language for Dart like Jinja or Stencil. 
version: 0.0.1

environment:
  sdk: '>=2.7.1 <3.0.0'

dependencies:
  petitparser: ^3.0.1

dev_dependencies:
  angular_ast: ^0.5.11
  pedantic: ^1.9.0