name: renderable
description: An simple (and not yet powerful) template language for Dart like Jinja or Stencil.
version: 0.0.4

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  analyzer: ^0.39.7
  build: ^1.2.2
  meta: ^1.1.8
  source_gen: ^0.9.5
  string_scanner: ^1.0.5

dev_dependencies:
  build_runner: ^1.9.0
  pedantic: ^1.9.0
