name: renderable
description: An simple (and not yet powerful) template language for Dart like Jinja or Stencil.
version: 0.0.6

environment:
  sdk: '>=2.8.4 <3.0.0'

dependencies:
  analyzer: any
  build: any
  meta: any
  path: any
  source_gen: any
  string_scanner: any

dev_dependencies:
  build_runner: any
  pedantic: any
  test: any
