name: renderable
description: Testing features for Jinja.dart.
version: 1.0.0-dev+43

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  build: any
  dart_style: any
  meta: ^1.3.0-nullsafety
  path: ^1.8.0-nullsafety
  stack_trace: ^1.10.0-nullsafety
  string_scanner: ^1.1.0-nullsafety

dev_dependencies:
  build_runner: any
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
