name: renderable
description: Testing features for Jinja.dart.
version: 1.0.0-dev+26

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  build: ^1.5.1
  dart_style: ^1.3.10
  meta: ^1.3.0-nullsafety
  path: ^1.8.0-nullsafety
  string_scanner: ^1.1.0-nullsafety

dev_dependencies:
  build_runner: ^1.10.6
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety
