name: renderable
description: An simple template language for Dart like Jinja or Stencil.
version: 1.0.0-alpha+8

environment:
  sdk: '>=2.9.3 <3.0.0'

dependencies:
  build: any
  meta: any
  path: any
  source_gen: any
  string_scanner: any

dev_dependencies:
  build_runner: any
  dart_style: any
  pedantic: any
  test: any
