name: textwrap
description: Text wrapping and filling. Python textwrap port for Dart.
version: 1.0.0-dev.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.2
